# ┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
# ┃                      Input Configuration                    ┃
# ┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛

# Input wiki https://wiki.hyprland.org/Configuring/Variables/#input

input {
    follow_mouse = 2 # 0|1|2|3
    float_switch_override_focus = 2
    kb_layout = pl
    sensitivity = 0.0          # Brak modyfikacji czułości (mnożnik 1.0)
    accel_profile = flat       # Wyłączenie krzywej akceleracji (ruch liniowy)
    force_no_accel = true      # Dodatkowe upewnienie się, że libinput nie doda nic od siebie
}
cursor{
    no_hardware_cursors = true
}

device {
    name = gaomon-gaomon-tablet_pd1610-1
    output = HDMI-A-1
}
