exec-once=dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
workspace = 2, always_keep_position
general {
    gaps_in = 1
    gaps_out = 1
    border_size = 1
}
workspace=gapsin:0,gapsout:0,bordersize:0


